import {
  IconDashboard,
  IconSettings,
  IconUsers,
  IconPlus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconDeviceFloppy,
  IconCheck,
  IconAlertTriangle,
  IconAlertCircle,
  IconInfoCircle,
  IconChevronDown,
  IconChevronUp,
  IconX,
  IconSquareCheck,
  IconSquareX,
  IconMenu2,
  IconMoon,
  IconSun,
  IconChartBar,
  IconPlayerPlay,
  IconRocket,
  IconBan,
  IconThumbUp,
  // New domain icons
  IconHome,
  IconInbox,
  IconCalendar,
  IconPhoto,
  IconHistory,
  IconUser,
  IconSend,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconPaperclip,
  IconUpload,
  IconDownload,
  IconPrinter,
  IconCopy,
  IconCopyPlus,
  IconChecks,
  IconClearAll,
  IconCamera,
  IconVideo,
  IconCameraRotate,
  IconBolt,
  IconBook,
  IconNotebook,
  IconCertificate,
  IconSchool,
  IconBooks,
  IconAward,
  IconMoodKid,
  IconUsersGroup,
  IconTarget,
  IconFlag,
  IconFlame,
  IconGift,
  IconLanguage,
  IconPalette,
  IconTrophy,
  IconCrown,
  IconPlayerPause,
  IconMessage,
  IconMail,
  IconRefresh,
  IconTrendingUp,
  IconTrendingDown,
  IconCurrencyDollar,
  IconLayoutGrid,
  IconList,
  IconDoorExit,
  IconBell,
  IconArrowLeft,
  IconEye,
  IconEyeOff,
  IconHelpCircle,
  IconFilter,
  IconArrowsSort,
  // New specific icons
  IconFileExport,
  IconFileImport,
  IconTrashOff,
  IconToggleLeft,
  IconLogin,
  IconUserPlus,
  IconShieldCheck,
  IconFileText,
  IconShare
} from '@tabler/icons-react';


/**
 * GdsIcons is the centralized semantic icon dictionary.
 * Applications MUST use these exported icons instead of importing
 * raw icons from tabler/icons-react directly. This ensures complete
 * visual consistency across the platform.
 */
export const GdsIcons = {
  // Navigation
  Dashboard: IconDashboard,
  Settings: IconSettings,
  Users: IconUsers,
  Analytics: IconChartBar,
  Home: IconHome,
  Inbox: IconInbox,
  Calendar: IconCalendar,
  Gallery: IconPhoto,
  History: IconHistory,
  Profile: IconUser,

  // Actions
  Add: IconPlus,
  Edit: IconEdit,
  Delete: IconTrash,
  Search: IconSearch,
  Save: IconDeviceFloppy,
  Play: IconPlayerPlay,
  Start: IconRocket,
  Send: IconSend,
  Reply: IconArrowBackUp,
  Forward: IconArrowForwardUp,
  Attach: IconPaperclip,
  Upload: IconUpload,
  Download: IconDownload,
  Print: IconPrinter,
  Copy: IconCopy,
  Duplicate: IconCopyPlus,
  Check: IconSquareCheck,
  Uncheck: IconSquareX,
  Complete: IconChecks,
  Clear: IconClearAll,
  Cancel: IconBan,
  Confirm: IconThumbUp,
  Close: IconX,

  // Preferences & System
  Language: IconLanguage,
  Theme: IconPalette,

  // Media
  Capture: IconCamera,
  Record: IconVideo,
  Flip: IconCameraRotate,
  Flash: IconBolt,

  // Domain specific
  Course: IconBook,
  Lesson: IconNotebook,
  Certificate: IconCertificate,
  Student: IconSchool,
  Class: IconBooks,
  Grade: IconAward,
  Child: IconMoodKid,
  Family: IconUsersGroup,
  Habit: IconTarget,
  Goal: IconFlag,
  Streak: IconFlame,
  Reward: IconGift,

  // Feedback
  Success: IconCheck,
  Warning: IconAlertTriangle,
  Danger: IconAlertCircle,
  Info: IconInfoCircle,

  // Analysis additions
  Trophy: IconTrophy,
  Crown: IconCrown,
  Pause: IconPlayerPause,
  Message: IconMessage,
  Mail: IconMail,
  Refresh: IconRefresh,
  TrendingUp: IconTrendingUp,
  TrendingDown: IconTrendingDown,
  Currency: IconCurrencyDollar,
  Grid: IconLayoutGrid,
  List: IconList,
  Logout: IconDoorExit,
  Notifications: IconBell,
  Back: IconArrowLeft,
  Eye: IconEye,
  EyeOff: IconEyeOff,
  Help: IconHelpCircle,
  Filter: IconFilter,
  Sort: IconArrowsSort,

  // New Audit-driven additions
  Export: IconFileExport,
  Import: IconFileImport,
  Preview: IconEye,
  Clone: IconCopy,
  Restore: IconTrashOff,
  Toggle: IconToggleLeft,
  Submit: IconCheck,
  Reset: IconRefresh,
  Login: IconLogin,
  Register: IconUserPlus,
  Verify: IconShieldCheck,
  Launch: IconRocket,
  Draft: IconFileText,
  Refer: IconShare,
  Evidence: IconPaperclip,

  // System
  ChevronDown: IconChevronDown,
  ChevronUp: IconChevronUp,
  Menu: IconMenu2,
  Moon: IconMoon,
  Sun: IconSun,
};
